/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_revesoft_itelmobiledialer_e2eencryption_rsa */

#ifndef _Included_com_revesoft_itelmobiledialer_e2eencryption_rsa
#define _Included_com_revesoft_itelmobiledialer_e2eencryption_rsa
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_revesoft_itelmobiledialer_e2eencryption_rsa
 * Method:    getEncryptedString
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_1revesoft_1itelmobiledialer_1e2eencryption_1rsa_getEncryptedString
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_revesoft_itelmobiledialer_e2eencryption_rsa
 * Method:    getDecryptedString
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_1revesoft_1itelmobiledialer_1e2eencryption_1rsa_getDecryptedString
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_revesoft_itelmobiledialer_e2eencryption_rsa
 * Method:    getEncryptedByte
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_1revesoft_1itelmobiledialer_1e2eencryption_1rsa_getEncryptedByte
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_revesoft_itelmobiledialer_e2eencryption_rsa
 * Method:    getDecryptedByte
 * Signature: ([BLjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_1revesoft_1itelmobiledialer_1e2eencryption_1rsa_getDecryptedByte
  (JNIEnv *, jobject, jbyteArray, jstring, jstring);

/*
 * Class:     com_revesoft_itelmobiledialer_e2eencryption_rsa
 * Method:    getCRTDecryptedString
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_1revesoft_1itelmobiledialer_1e2eencryption_1rsa_getCRTDecryptedString
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     com_revesoft_itelmobiledialer_e2eencryption_rsa
 * Method:    getCRTDecryptedByte
 * Signature: ([BLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_1revesoft_1itelmobiledialer_1e2eencryption_1rsa_getCRTDecryptedByte
  (JNIEnv *, jobject, jbyteArray, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
